const cards = [
  // {
  //   number: 2,
  //   kind: "Hearts",
  //   key: 1,
  //   index: 1,
  //   image: "./images/2H.jpg",
  // },
  // {
  //   number: 3,
  //   kind: "Hearts",
  //   key: 2,
  //   index: 2,
  //   image: "./images/3H.jpg",
  // },
  // {
  //   number: 4,
  //   kind: "Hearts",
  //   key: 3,
  //   index: 3,
  //   image: "./images/4H.jpg",
  // },
  // {
  //   number: 5,
  //   kind: "Hearts",
  //   key: 4,
  //   index: 4,
  //   image: "./images/5H.jpg",
  // },
  {
    number: 6,
    kind: "Hearts",
    key: 5,
    index: 5,
    image: "./images/6H.jpg",
  },
  {
    number: 7,
    kind: "Hearts",
    key: 6,
    index: 6,
    image: "./images/7H.jpg",
  },
  {
    number: 8,
    kind: "Hearts",
    key: 7,
    index: 7,
    image: "./images/8H.jpg",
  },
  {
    number: 9,
    kind: "Hearts",
    key: 8,
    index: 8,
    image: "./images/9H.jpg",
  },
  {
    number: 10,
    kind: "Hearts",
    key: 9,
    index: 9,
    image: "./images/10H.jpg",
  },
  {
    number: 11,
    kind: "Hearts",
    key: 10,
    index: 10,
    image: "./images/JH.jpg",
  },
  {
    number: 12,
    kind: "Hearts",
    key: 11,
    index: 11,
    image: "./images/QH.jpg",
  },
  {
    number: 13,
    kind: "Hearts",
    key: 12,
    index: 12,
    image: "./images/KH.jpg",
  },
  {
    number: 14,
    kind: "Hearts",
    key: 13,
    index: 13,
    image: "./images/AH.jpg",
  },
  // {
  //   number: 2,
  //   kind: "Diamonds",
  //   key: 14,
  //   index: 14,
  //   image: "./images/2D.jpg",
  // },
  // {
  //   number: 3,
  //   kind: "Diamonds",
  //   key: 15,
  //   index: 15,
  //   image: "./images/3D.jpg",
  // },
  // {
  //   number: 4,
  //   kind: "Diamonds",
  //   key: 16,
  //   index: 16,
  //   image: "./images/4D.jpg",
  // },
  // {
  //   number: 5,
  //   kind: "Diamonds",
  //   key: 17,
  //   index: 17,
  //   image: "./images/5D.jpg",
  // },
  {
    number: 6,
    kind: "Diamonds",
    key: 18,
    index: 18,
    image: "./images/6D.jpg",
  },
  {
    number: 7,
    kind: "Diamonds",
    key: 19,
    index: 19,
    image: "./images/7D.jpg",
  },
  {
    number: 8,
    kind: "Diamonds",
    key: 20,
    index: 20,
    image: "./images/8D.jpg",
  },
  {
    number: 9,
    kind: "Diamonds",
    key: 21,
    index: 21,
    image: "./images/9D.jpg",
  },
  {
    number: 10,
    kind: "Diamonds",
    key: 22,
    index: 22,
    image: "./images/10D.jpg",
  },
  {
    number: 11,
    kind: "Diamonds",
    key: 23,
    index: 23,
    image: "./images/JD.jpg",
  },
  {
    number: 12,
    kind: "Diamonds",
    key: 24,
    index: 24,
    image: "./images/QD.jpg",
  },
  {
    number: 13,
    kind: "Diamonds",
    key: 25,
    index: 25,
    image: "./images/KD.jpg",
  },
  {
    number: 14,
    kind: "Diamonds",
    key: 26,
    index: 26,
    image: "./images/AD.jpg",
  },
  // {
  //   number: 2,
  //   kind: "Spades",
  //   key: 27,
  //   index: 27,
  //   image: "./images/2S.jpg",
  // },
  // {
  //   number: 3,
  //   kind: "Spades",
  //   key: 28,
  //   index: 28,
  //   image: "./images/3S.jpg",
  // },
  // {
  //   number: 4,
  //   kind: "Spades",
  //   key: 29,
  //   index: 29,
  //   image: "./images/4S.jpg",
  // },
  // {
  //   number: 5,
  //   kind: "Spades",
  //   key: 30,
  //   index: 30,
  //   image: "./images/5S.jpg",
  // },
  {
    number: 6,
    kind: "Spades",
    key: 31,
    index: 31,
    image: "./images/6S.jpg",
  },
  {
    number: 7,
    kind: "Spades",
    key: 32,
    index: 32,
    image: "./images/7S.jpg",
  },
  {
    number: 8,
    kind: "Spades",
    key: 33,
    index: 33,
    image: "./images/8S.jpg",
  },
  {
    number: 9,
    kind: "Spades",
    key: 34,
    index: 34,
    image: "./images/9S.jpg",
  },
  {
    number: 10,
    kind: "Spades",
    key: 35,
    index: 35,
    image: "./images/10S.jpg",
  },
  {
    number: 11,
    kind: "Spades",
    key: 36,
    index: 36,
    image: "./images/JS.jpg",
  },
  {
    number: 12,
    kind: "Spades",
    key: 37,
    index: 37,
    image: "./images/QS.jpg",
  },
  {
    number: 13,
    kind: "Spades",
    key: 38,
    index: 38,
    image: "./images/KS.jpg",
  },
  {
    number: 14,
    kind: "Spades",
    key: 39,
    index: 39,
    image: "./images/AS.jpg",
  },
  // {
  //   number: 2,
  //   kind: "Clubs",
  //   key: 40,
  //   index: 40,
  //   image: "./images/2C.jpg",
  // },
  // {
  //   number: 3,
  //   kind: "Clubs",
  //   key: 41,
  //   index: 41,
  //   image: "./images/3C.jpg",
  // },
  // {
  //   number: 4,
  //   kind: "Clubs",
  //   key: 42,
  //   index: 42,
  //   image: "./images/4C.jpg",
  // },
  // {
  //   number: 5,
  //   kind: "Clubs",
  //   key: 43,
  //   index: 43,
  //   image: "./images/5C.jpg",
  // },
  {
    number: 6,
    kind: "Clubs",
    key: 44,
    index: 44,
    image: "./images/6C.jpg",
  },
  {
    number: 7,
    kind: "Clubs",
    key: 45,
    index: 45,
    image: "./images/7C.jpg",
  },
  {
    number: 8,
    kind: "Clubs",
    key: 46,
    index: 46,
    image: "./images/8C.jpg",
  },
  {
    number: 9,
    kind: "Clubs",
    key: 47,
    index: 47,
    image: "./images/9C.jpg",
  },
  {
    number: 10,
    kind: "Clubs",
    key: 48,
    index: 48,
    image: "./images/10C.jpg",
  },
  {
    number: 11,
    kind: "Clubs",
    key: 49,
    index: 49,
    image: "./images/JC.jpg",
  },
  {
    number: 12,
    kind: "Clubs",
    key: 50,
    index: 50,
    image: "./images/QC.jpg",
  },
  {
    number: 13,
    kind: "Clubs",
    key: 51,
    index: 51,
    image: "./images/KC.jpg",
  },
  {
    number: 14,
    kind: "Clubs",
    key: 52,
    index: 52,
    image: "./images/AC.jpg",
  }
]

export default cards;